version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1578850073
layout:
  /header/:
    -
      - 'logo-2411 30'
      - 'spacer-7871 70'
  /navigation/:
    -
      - menu-1369
  /main/:
    -
      - system-content-9615
  /footer/:
    -
      - position-footer
    -
      - 'copyright-9002 40'
      - 'spacer-5578 30'
      - 'branding-8181 30'
  offcanvas:
    -
      - mobile-menu-7312
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
