version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1578850073
layout:
  /header/:
    -
      - 'logo-7190 30'
      - 'spacer-2953 70'
  /main/:
    -
      - system-messages-1142
    -
      - system-content-4228
  /footer/:
    -
      - position-footer
    -
      - 'copyright-8586 40'
      - 'spacer-1691 30'
      - 'branding-7520 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
