name: '10'
timestamp: 1578850073
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1578850073
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-7708: Menu
  sample:
    sample-1: 'Gantry 5'
    sample-2: 'Getting Started'
    sample-3: 'Key Features'
  messages:
    system-messages-1575: 'System Messages'
  position:
    position-footer: Footer
  copyright:
    copyright-3735: Copyright
  social:
    social-9258: Social
  branding:
    branding-3784: Branding
  mobile-menu:
    mobile-menu-4216: 'Mobile Menu'
inherit: {  }
